### ISSUE TITLE
Use jupyter notebooks instead of latex files to report results

### ISSUE THREAD

**Issue by Roj** [Roj/recsys-comparison#1]
Basically, title.

It's easier to see results and to re-run them.

Note: this also implies that there should be a results folders with only the .csv that lists the metrics' values for each algorithm (one dataset per file).

**Comment by dminones** [comment]
Issue Solved. This issue opens a few questions though.

- Should we automate the copy from build to data-analyisis?
- We could have a analysis for each dataset with data about cross fold distribuition, etc.
