### ISSUE TITLE
Polymorphism in the gradle file

### ISSUE THREAD

**Issue by Roj** [Roj/recsys-comparison#2]
Currently, the crossfold and similar tasks change their behaviour based on the specified dataset. 

Instead of having a method with different behaviour for each possible state, we should have different methods that do the task for a specific dataset (i.e. crossfoldML100k, crossfoldBookCrossing, etc.)

**Comment by dminones** [comment]
Should we use this pattern in order to avoid having a big build.gradle with all the datasets?

https://docs.gradle.org/current/userguide/organizing_build_logic.html#sec:configuring_using_external_script

**Comment by Roj** [comment]
Sounds good. Maybe we could have a `.gradle` file for each algorithm where we write the fetch, crossfold and evaluate tasks. 

For example, we could add a folder for each algorithm in `algorithms/`, and group in that folder the `.groovy` and `.build`. The `.build` would, for lastfm as an example, include: `fetchLastfm`, `crossfoldLastfm` and `evaluateLastfm` tasks.

What do you think?

**Comment by dminones** [comment]
Actually would be for each dataset right? Because we already have a .groovy file for each algorithm but each dataset needs this tasks: fetchLastfm, crossfoldLastfm and evaluateLastfm.

**Comment by Roj** [comment]
You're right, I messed that up. Then a folder for each dataset? Maybe grouped with the .yml file?
