### ISSUE TITLE
Paralell plot of nDCG

### ISSUE THREAD

**Issue by lrargerich** [Roj/recsys-comparison#9]
Check if this plot is right or if we have to invert it.

**Comment by Roj** [comment]
![image](https://cloud.githubusercontent.com/assets/290523/23197370/a4314de4-f89e-11e6-954b-5f18d7812b97.png)

that's how the plot looks. I don't think it is inverted, unless I'm not seeing something.

By the way, I realise the ticks do not work well with this metric (that requires more decimals), I've added an issue for that #11
